#!/bin/bash

function=$(ls -l | grep -E "*.c$" | wc -l)

if [[ $function -gt 0  &&  $# -ne 0 ]]
then
	error=$(betty $@ | grep -e "[WARNING|ERROR]" | grep -v "README.md" | wc -l)
else 
	echo -e "No files to verify"
	exit
fi
if [ $error -gt 0 ]
then
	echo -e "Errors !"
	betty $@
else
	echo -e "No errors !"
	git add $@
	echo -e "git add $@"
fi
